from tkinter import*
from tkinter import ttk
import random
import tkinter.messagebox
import time
import mysql.connector as mysql
from mysql.connector import cursor
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from fpdf import FPDF
import Database

class Train:
    def __init__(self,root):
        self.root=root
        self.root.title=("Train Reservation")
        self.root.geometry("1350x800+0+0")
        self.root.configure(background='gainsboro')

        MainFrame= Frame(self.root, bd=10, width=1350, height=700, bg='gainsboro', relief=RIDGE)
        MainFrame.grid()
        TopFrame1 = Frame(MainFrame, bd=10, width=1340, height=100, bg='gainsboro', relief=RIDGE)
        TopFrame1.grid()
        TopFrame2 = Frame(MainFrame, bd=10, width=1300, height=500, bg='gainsboro', relief=RIDGE)
        TopFrame2.grid()
        f1 = Frame(TopFrame2, width=890, height=500, bd=5, relief=RIDGE)
        f1.grid(row=1, column=0)
        f2 = Frame(TopFrame2, width=400, height=500,pady=2, bd=5, relief=RIDGE)
        f2.grid(row=1, column=1)

        frametopRight= Frame(f2, width=404, height=500, pady=2, bd=5, relief=RIDGE)
        frametopRight.pack(side=TOP)
        frameBottomRight=Frame(f2, width=408, height=100, bd=5, pady=15, relief=RIDGE)
        frameBottomRight.pack(side=TOP)
        f1a=Frame(f1, width=900, height=330, bd=5, relief=RIDGE)
        f1a.pack(side=TOP)
        f2a=Frame(f1, width=900, height=330, bd=5, relief=RIDGE)
        f2a.pack(side=BOTTOM)

        topLeft1= Frame(f1a, width=300, height=200, bd=5, padx=20, pady=1, relief=RIDGE)
        topLeft1.pack(side=LEFT)
        topLeft2= Frame(f1a, width=300, height=200, bd=5, relief=RIDGE)
        topLeft2.pack(side=RIGHT)
        topLeft3= Frame(f1a, width=300, height=200, bd=5, pady=5, relief=RIDGE)
        topLeft3.pack(side=RIGHT)

        bottomLeft1= Frame(f2a, width=450, height=300, bd=5, pady=12, relief=RIDGE)
        bottomLeft1.pack(side=LEFT)

        bottomLeft2=Frame(f2a, width=450, height=300, bd=5, relief=RIDGE)
        bottomLeft2.pack(side=RIGHT)
#=============================================================================================
        lblTitle=Label(TopFrame1,font=('arial',40,'bold'),text="Train Reservation",bd=5,width=41,padx=4,justify='center')
        lblTitle.grid(row=0, column=0)
#================================================================================================
        Date1=StringVar()
        time1=StringVar()
        Ticketclass=StringVar()
        TicketPrice= StringVar()
        Child_Ticket= StringVar()
        Adult_Ticket=StringVar()
        From_Destination=StringVar()
        To_Destination=StringVar()
        Fee_Price=StringVar()
        Route=StringVar()
        Reciept_Ref=StringVar()

        text_Input=StringVar()
        global operator
        operator=""

        Ticketclass.set("")
        TicketPrice.set("")
        Child_Ticket.set("")
        Adult_Ticket.set("")
        From_Destination.set("")
        To_Destination.set("")
        Fee_Price.set("")
        Route.set("")
        Reciept_Ref.set("")

        var1=IntVar()
        var2=IntVar()
        var3=IntVar()
        var4=IntVar()
        var5=IntVar()
        var6=StringVar()
        var7=StringVar()
        var8=StringVar()
        var9=StringVar()
        var10=IntVar()
        var11=IntVar()
        var12=IntVar()

        Tax= StringVar()
        SubTotal=StringVar()
        Total=StringVar()
        Name=StringVar()
        Age=StringVar()
        Email=StringVar()

        var1.set("0")
        var2.set("0")
        var3.set("0")
        var4.set("0")
        var5.set("0")
        var6.set("0")
        var7.set("0")
        var8.set("0")
        var9.set("0")
        var10.set("0")
        var11.set("0")
        var12.set("0")

#########################################################Function Declaraion#################################################
        def iExit():
            iExit=tkinter.messagebox.askyesno("Train Ticket System","Cofirm if you want to quit")
            if iExit >0:
                root.destroy()
                return
        def Reset():
            var1.set("0")
            var2.set("0")
            var3.set("0")
            var4.set("0")
            var5.set("0")
            var6.set("0")
            var7.set("0")
            var8.set("0")
            var9.set("0")
            var10.set("0")
            var11.set("0")
            var12.set("0")
            Tax.set("0")
            SubTotal.set("0")
            Total.set("0")
            Name.set("0")
            Age.set("0")
            Email .set("0")
            Ticketclass.set("")
            TicketPrice.set("")
            Child_Ticket.set("")
            Adult_Ticket.set("")
            From_Destination.set("")
            To_Destination.set("")
            Fee_Price.set("")
            Route.set("")
            Reciept_Ref.set("")
        def Travel_Cost():
            if(var9.get()=="Delhi->Kanpur" and var1.get()==1 and var4.get()==1):
                Tcost= float(50.6)
                Single=float(var12.get())
                Adult_Tax="Rs.",str('%.2f'% ((Tcost*Single)*0.05))
                Adult_Fees="Rs.",str('%.2f'% ((Tcost*Single)))
                TotalCost="Rs.",str('%.2f'%((Tcost*Single)+((Tcost*Single)*0.05)))
                Tax.set(Adult_Tax)
                SubTotal.set(Adult_Fees)
                Ticketclass.set("Standard")
                TicketPrice.set(Adult_Fees)
                Child_Ticket.set("NO")
                Adult_Ticket.set("Yes")
                From_Destination.set("Delhi")
                To_Destination.set("Kanpur")
                Fee_Price.set(TotalCost)
                Total.set(TotalCost)
                Route.set("Direct")

                x=random.randit(109,5876)
                randomRef=str(x)
                Reciept_Ref.set("TFL"+randomRef)
            elif(var9.get()=="Delhi->Kanpur" and var1.get()==1 and var5.get()==1):
                Tcost= float(80.9)
                Single=float(var12.get())
                Adult_Tax="Rs.",str('%.2f'% ((Tcost*Single)*0.05))
                Adult_Fees="Rs.",str('%.2f'% ((Tcost*Single)))
                TotalCost="Rs.",str('%.2f'%((Tcost*Single)+((Tcost*Single)*0.05)))
                Tax.set(Adult_Tax)
                SubTotal.set(Adult_Fees)
                Ticketclass.set("Standard")
                TicketPrice.set(Adult_Fees)
                Child_Ticket.set("NO")
                Adult_Ticket.set("Yes")
                From_Destination.set("Delhi")
                To_Destination.set("Kanpur")
                Fee_Price.set(TotalCost)
                Total.set(TotalCost)
                Route.set("Direct")

                x=random.randit(109,5876)
                randomRef=str(x)
                Reciept_Ref.set("TFL"+randomRef)
            elif (var9.get() == "Kanpur->Chandigarh" and var1.get() == 1 and var4.get() == 1):
                Tcost = float(80.3)
                Single = float(var12.get())
                Adult_Tax = "Rs.", str('%.2f' % ((Tcost * Single) * 0.05))
                Adult_Fees = "Rs.", str('%.2f' % ((Tcost * Single)))
                TotalCost = "Rs.", str('%.2f' % ((Tcost * Single) + ((Tcost * Single) * 0.05)))
                Tax.set(Adult_Tax)
                SubTotal.set(Adult_Fees)
                Ticketclass.set("Standard")
                TicketPrice.set(Adult_Fees)
                Child_Ticket.set("NO")
                Adult_Ticket.set("Yes")
                From_Destination.set("Kanpur")
                To_Destination.set("Chandigarh")
                Fee_Price.set(TotalCost)
                Total.set(TotalCost)
                Route.set("Direct")

                x = random.randit(109, 5876)
                randomRef = str(x)
                Reciept_Ref.set("TFL" + randomRef)
            elif (var9.get() == "Kanpur->Chandigarh" and var1.get() == 1 and var5.get() == 1):
                Tcost = float(45.3)
                Single = float(var12.get())
                Adult_Tax = "Rs.", str('%.2f' % ((Tcost * Single) * 0.05))
                Adult_Fees = "Rs.", str('%.2f' % ((Tcost * Single)))
                TotalCost = "Rs.", str('%.2f' % ((Tcost * Single) + ((Tcost * Single) * 0.05)))
                Tax.set(Adult_Tax)
                SubTotal.set(Adult_Fees)
                Ticketclass.set("Standard")
                TicketPrice.set(Adult_Fees)
                Child_Ticket.set("NO")
                Adult_Ticket.set("Yes")
                From_Destination.set("Kanpur")
                To_Destination.set("Chandigarh")
                Fee_Price.set(TotalCost)
                Total.set(TotalCost)
                Route.set("Direct")

                x = random.randit(109, 5876)
                randomRef = str(x)
                Reciept_Ref.set("TFL" + randomRef)

            elif(var9.get() == "Chandigarh->Pune" and var1.get() == 1 and var4.get() == 1):
                Tcost = float(45.32)
                Single = float(var12.get())
                Adult_Tax = "Rs.", str('%.2f' % ((Tcost * Single) * 0.05))
                Adult_Fees = "Rs.", str('%.2f' % ((Tcost * Single)))
                TotalCost = "Rs.", str('%.2f' % ((Tcost * Single) + ((Tcost * Single) * 0.05)))
                Tax.set(Adult_Tax)
                SubTotal.set(Adult_Fees)
                Ticketclass.set("Standard")
                TicketPrice.set(Adult_Fees)
                Child_Ticket.set("NO")
                Adult_Ticket.set("Yes")
                From_Destination.set("Chandigarh")
                To_Destination.set("Pune")
                Fee_Price.set(TotalCost)
                Total.set(TotalCost)
                Route.set("Direct")

                x = random.randit(109, 5876)
                randomRef = str(x)
                Reciept_Ref.set("TFL" + randomRef)
            elif (var9.get() == "Chandigarh->Pune" and var1.get() == 1 and var5.get() == 1):
                Tcost = float(75.21)
                Single = float(var12.get())
                Adult_Tax = "Rs.", str('%.2f' % ((Tcost * Single) * 0.05))
                Adult_Fees = "Rs.", str('%.2f' % ((Tcost * Single)))
                TotalCost = "Rs.", str('%.2f' % ((Tcost * Single) + ((Tcost * Single) * 0.05)))
                Tax.set(Adult_Tax)
                SubTotal.set(Adult_Fees)
                Ticketclass.set("Standard")
                TicketPrice.set(Adult_Fees)
                Child_Ticket.set("NO")
                Adult_Ticket.set("Yes")
                From_Destination.set("Chandigarh")
                To_Destination.set("Pune")
                # Fee_Price.set(TotalCost)
                Total.set(TotalCost)
                Route.set("Direct")

                x = random.randit(109, 5876)
                randomRef = str(x)
                Reciept_Ref.set("TFL" + randomRef)
            elif (var9.get() == "Mumbai->Goa" and var1.get() == 1 and var4.get() == 1):
                Tcost = float(95.2)
                Single = float(var12.get())
                Adult_Tax = "Rs.", str('%.2f' % ((Tcost * Single) * 0.05))
                Adult_Fees = "Rs.", str('%.2f' % ((Tcost * Single)))
                TotalCost = "Rs.", str('%.2f' % ((Tcost * Single) + ((Tcost * Single) * 0.05)))
                Tax.set(Adult_Tax)
                SubTotal.set(Adult_Fees)
                Ticketclass.set("Standard")
                TicketPrice.set(Adult_Fees)
                Child_Ticket.set("NO")
                Adult_Ticket.set("Yes")
                From_Destination.set("Mumbai")
                To_Destination.set("Goa")
                Fee_Price.set(TotalCost)
                Total.set(TotalCost)
                Route.set("Direct")

                x = random.randit(109, 5876)
                randomRef = str(x)
                Reciept_Ref.set("TFL" + randomRef)
            elif (var9.get() == "Mumbai->Goa" and var1.get() == 1 and var5.get() == 1):
                Tcost = float(84.3)
                Single = float(var12.get())
                Adult_Tax = "Rs.", str('%.2f' % ((Tcost * Single) * 0.05))
                Adult_Fees = "Rs.", str('%.2f' % ((Tcost * Single)))
                TotalCost = "Rs.", str('%.2f' % ((Tcost * Single) + ((Tcost * Single) * 0.05)))
                Tax.set(Adult_Tax)
                SubTotal.set(Adult_Fees)
                Ticketclass.set("Standard")
                TicketPrice.set(Adult_Fees)
                Child_Ticket.set("NO")
                Adult_Ticket.set("Yes")
                From_Destination.set("Mumbai")
                To_Destination.set("Goa")
                Fee_Price.set(TotalCost)
                Total.set(TotalCost)
                Route.set("Direct")

                x = random.randit(109, 5876)
                randomRef = str(x)
                Reciept_Ref.set("TFL" + randomRef)
 ################Economy##################################################
            elif (var9.get() == "Delhi->Kanpur" and var2.get() == 1 and var4.get() == 1):
                Tcost = float(50.6)
                Single = float(var12.get())
                Adult_Tax = "Rs.", str('%.2f' % ((Tcost * Single) * 0.05))
                Adult_Fees = "Rs.", str('%.2f' % ((Tcost * Single)))
                TotalCost = "Rs.", str('%.2f' % ((Tcost * Single) + ((Tcost * Single) * 0.05)))
                Tax.set(Adult_Tax)
                SubTotal.set(Adult_Fees)
                Ticketclass.set("Standard")
                TicketPrice.set(Adult_Fees)
                Child_Ticket.set("NO")
                Adult_Ticket.set("Yes")
                From_Destination.set("Delhi")
                To_Destination.set("Kanpur")
                Fee_Price.set(TotalCost)
                Total.set(TotalCost)
                Route.set("Direct")

                x = random.randit(109, 5876)
                randomRef = str(x)
                Reciept_Ref.set("TFL" + randomRef)
            elif (var9.get() == "Delhi->Kanpur" and var2.get() == 1 and var5.get() == 1):
                Tcost = float(80.9)
                Single = float(var12.get())
                Adult_Tax = "Rs.", str('%.2f' % ((Tcost * Single) * 0.05))
                Adult_Fees = "Rs.", str('%.2f' % ((Tcost * Single)))
                TotalCost = "Rs.", str('%.2f' % ((Tcost * Single) + ((Tcost * Single) * 0.05)))
                Tax.set(Adult_Tax)
                SubTotal.set(Adult_Fees)
                Ticketclass.set("Standard")
                TicketPrice.set(Adult_Fees)
                Child_Ticket.set("NO")
                Adult_Ticket.set("Yes")
                From_Destination.set("Delhi")
                To_Destination.set("Kanpur")
                Fee_Price.set(TotalCost)
                Total.set(TotalCost)
                Route.set("Direct")

                x = random.randit(109, 5876)
                randomRef = str(x)
                Reciept_Ref.set("TFL" + randomRef)
            elif (var9.get() == "Kanpur->Chandigarh" and var2.get() == 1 and var4.get() == 1):
                Tcost = float(80.3)
                Single = float(var12.get())
                Adult_Tax = "Rs.", str('%.2f' % ((Tcost * Single) * 0.05))
                Adult_Fees = "Rs.", str('%.2f' % ((Tcost * Single)))
                TotalCost = "Rs.", str('%.2f' % ((Tcost * Single) + ((Tcost * Single) * 0.05)))
                Tax.set(Adult_Tax)
                SubTotal.set(Adult_Fees)
                Ticketclass.set("Standard")
                TicketPrice.set(Adult_Fees)
                Child_Ticket.set("NO")
                Adult_Ticket.set("Yes")
                From_Destination.set("Kanpur")
                To_Destination.set("Chandigarh")
                Fee_Price.set(TotalCost)
                Total.set(TotalCost)
                Route.set("Direct")

                x = random.randit(109, 5876)
                randomRef = str(x)
                Reciept_Ref.set("TFL" + randomRef)
            elif (var9.get() == "Kanpur->Chandigarh" and var2.get() == 1 and var5.get() == 1):
                Tcost = float(45.3)
                Single = float(var12.get())
                Adult_Tax = "Rs.", str('%.2f' % ((Tcost * Single) * 0.05))
                Adult_Fees = "Rs.", str('%.2f' % ((Tcost * Single)))
                TotalCost = "Rs.", str('%.2f' % ((Tcost * Single) + ((Tcost * Single) * 0.05)))
                Tax.set(Adult_Tax)
                SubTotal.set(Adult_Fees)
                Ticketclass.set("Standard")
                TicketPrice.set(Adult_Fees)
                Child_Ticket.set("NO")
                Adult_Ticket.set("Yes")
                From_Destination.set("Kanpur")
                To_Destination.set("Chandigarh")
                Fee_Price.set(TotalCost)
                Total.set(TotalCost)
                Route.set("Direct")

                x = random.randit(109, 5876)
                randomRef = str(x)
                Reciept_Ref.set("TFL" + randomRef)

            elif (var9.get() == "Chandigarh->Pune" and var2.get() == 1 and var4.get() == 1):
                Tcost = float(80.32)
                Single = float(var12.get())
                Adult_Tax = "Rs.", str('%.2f' % ((Tcost * Single) * 0.05))
                Adult_Fees = "Rs.", str('%.2f' % ((Tcost * Single)))
                TotalCost = "Rs.", str('%.2f' % ((Tcost * Single) + ((Tcost * Single) * 0.05)))
                Tax.set(Adult_Tax)
                SubTotal.set(Adult_Fees)
                Ticketclass.set("Standard")
                TicketPrice.set(Adult_Fees)
                Child_Ticket.set("NO")
                Adult_Ticket.set("Yes")
                From_Destination.set("Chandigarh")
                To_Destination.set("Pune")
                Fee_Price.set(TotalCost)
                Total.set(TotalCost)
                Route.set("Direct")

                x = random.randit(109, 5876)
                randomRef = str(x)
                Reciept_Ref.set("TFL" + randomRef)
            elif (var9.get() == "Chandigarh->Pune" and var2.get() == 1 and var5.get() == 1):
                Tcost = float(75.21)
                Single = float(var12.get())
                Adult_Tax = "Rs.", str('%.2f' % ((Tcost * Single) * 0.05))
                Adult_Fees = "Rs.", str('%.2f' % ((Tcost * Single)))
                TotalCost = "Rs.", str('%.2f' % ((Tcost * Single) + ((Tcost * Single) * 0.05)))
                Tax.set(Adult_Tax)
                SubTotal.set(Adult_Fees)
                Ticketclass.set("Standard")
                TicketPrice.set(Adult_Fees)
                Child_Ticket.set("NO")
                Adult_Ticket.set("Yes")
                From_Destination.set("Chandigarh")
                To_Destination.set("Pune")
                Fee_Price.set(TotalCost)
                Total.set(TotalCost)
                Route.set("Direct")

                x = random.randit(109, 5876)
                randomRef = str(x)
                Reciept_Ref.set("TFL" + randomRef)
            elif (var9.get() == "Mumbai->Goa" and var2.get() == 1 and var4.get() == 1):
                Tcost = float(95.2)
                Single = float(var12.get())
                Adult_Tax = "Rs.", str('%.2f' % ((Tcost * Single) * 0.05))
                Adult_Fees = "Rs.", str('%.2f' % ((Tcost * Single)))
                TotalCost = "Rs.", str('%.2f' % ((Tcost * Single) + ((Tcost * Single) * 0.05)))
                Tax.set(Adult_Tax)
                SubTotal.set(Adult_Fees)
                Ticketclass.set("Standard")
                TicketPrice.set(Adult_Fees)
                Child_Ticket.set("NO")
                Adult_Ticket.set("Yes")
                From_Destination.set("Mumbai")
                To_Destination.set("Goa")
                Fee_Price.set(TotalCost)
                Total.set(TotalCost)
                Route.set("Direct")

                x = random.randit(109, 5876)
                randomRef = str(x)
                Reciept_Ref.set("TFL" + randomRef)
            elif (var9.get() == "Mumbai->Goa" and var2.get() == 1 and var5.get() == 1):
                Tcost = float(84.3)
                Single = float(var12.get())
                Adult_Tax = "Rs.", str('%.2f' % ((Tcost * Single) * 0.05))
                Adult_Fees = "Rs.", str('%.2f' % ((Tcost * Single)))
                TotalCost = "Rs.", str('%.2f' % ((Tcost * Single) + ((Tcost * Single) * 0.05)))
                Tax.set(Adult_Tax)
                SubTotal.set(Adult_Fees)
                Ticketclass.set("Standard")
                TicketPrice.set(Adult_Fees)
                Child_Ticket.set("NO")
                Adult_Ticket.set("Yes")
                From_Destination.set("Mumbai")
                To_Destination.set("Goa")
                Fee_Price.set(TotalCost)
                Total.set(TotalCost)
                Route.set("Direct")

                x = random.randit(109, 5876)
                randomRef = str(x)
                Reciept_Ref.set("TFL" + randomRef)
##################Firstclass###############################
            elif(var9.get() == "Delhi->Kanpur" and var3.get() == 1 and var4.get() == 1):

                Tcost = float(50.6)
                Single = float(var12.get())
                Adult_Tax = "Rs.", str('%.2f' % ((Tcost * Single) * 0.05))
                Adult_Fees = "Rs.", str('%.2f' % ((Tcost * Single)))
                TotalCost = "Rs.", str('%.2f' % ((Tcost * Single) + ((Tcost * Single) * 0.05)))
                Tax.set(Adult_Tax)
                SubTotal.set(Adult_Fees)
                Ticketclass.set("Standard")
                TicketPrice.set(Adult_Fees)
                Child_Ticket.set("NO")
                Adult_Ticket.set("Yes")
                From_Destination.set("Delhi")
                To_Destination.set("Kanpur")
                Fee_Price.set(TotalCost)
                Total.set(TotalCost)
                Route.set("Direct")

                x = random.randit(109, 5876)
                randomRef = str(x)
                Reciept_Ref.set("TFL" + randomRef)
            elif (var9.get() == "Delhi->Kanpur" and var3.get() == 1 and var5.get() == 1):
                Tcost = float(80.9)
                Single = float(var12.get())
                Adult_Tax = "Rs.", str('%.2f' % ((Tcost * Single) * 0.05))
                Adult_Fees = "Rs.", str('%.2f' % ((Tcost * Single)))
                TotalCost = "Rs.", str('%.2f' % ((Tcost * Single) + ((Tcost * Single) * 0.05)))
                Tax.set(Adult_Tax)
                SubTotal.set(Adult_Fees)
                Ticketclass.set("Standard")
                TicketPrice.set(Adult_Fees)
                Child_Ticket.set("NO")
                Adult_Ticket.set("Yes")
                From_Destination.set("Delhi")
                To_Destination.set("Kanpur")
                Fee_Price.set(TotalCost)
                Total.set(TotalCost)
                Route.set("Direct")

                x = random.randit(109, 5876)
                randomRef = str(x)
                Reciept_Ref.set("TFL" + randomRef)
            elif (var9.get() == "Kanpur->Chandigarh" and var3.get() == 1 and var4.get() == 1):
                Tcost = float(80.3)
                Single = float(var12.get())
                Adult_Tax = "Rs.", str('%.2f' % ((Tcost * Single) * 0.05))
                Adult_Fees = "Rs.", str('%.2f' % ((Tcost * Single)))
                TotalCost = "Rs.", str('%.2f' % ((Tcost * Single) + ((Tcost * Single) * 0.05)))
                Tax.set(Adult_Tax)
                SubTotal.set(Adult_Fees)
                Ticketclass.set("Standard")
                TicketPrice.set(Adult_Fees)
                Child_Ticket.set("NO")
                Adult_Ticket.set("Yes")
                From_Destination.set("Kanpur")
                To_Destination.set("Chandigarh")
                Fee_Price.set(TotalCost)
                Total.set(TotalCost)
                Route.set("Direct")

                x = random.randit(109, 5876)
                randomRef = str(x)
                Reciept_Ref.set("TFL" + randomRef)
            elif (var9.get() == "Kanpur->Chandigarh" and var3.get() == 1 and var5.get() == 1):
                Tcost = float(45.3)
                Single = float(var12.get())
                Adult_Tax = "Rs.", str('%.2f' % ((Tcost * Single) * 0.05))
                Adult_Fees = "Rs.", str('%.2f' % ((Tcost * Single)))
                TotalCost = "Rs.", str('%.2f' % ((Tcost * Single) + ((Tcost * Single) * 0.05)))
                Tax.set(Adult_Tax)
                SubTotal.set(Adult_Fees)
                Ticketclass.set("Standard")
                TicketPrice.set(Adult_Fees)
                Child_Ticket.set("NO")
                Adult_Ticket.set("Yes")
                From_Destination.set("Kanpur")
                To_Destination.set("Chandigarh")
                Fee_Price.set(TotalCost)
                Total.set(TotalCost)
                Route.set("Direct")

                x = random.randit(109, 5876)
                randomRef = str(x)
                Reciept_Ref.set("TFL" + randomRef)

            elif (var9.get() == "Chandigarh->Pune" and var3.get() == 1 and var4.get() == 1):
                Tcost = float(80.32)
                Single = float(var12.get())
                Adult_Tax = "Rs.", str('%.2f' % ((Tcost * Single) * 0.05))
                Adult_Fees = "Rs.", str('%.2f' % ((Tcost * Single)))
                TotalCost = "Rs.", str('%.2f' % ((Tcost * Single) + ((Tcost * Single) * 0.05)))
                Tax.set(Adult_Tax)
                SubTotal.set(Adult_Fees)
                Ticketclass.set("Standard")
                TicketPrice.set(Adult_Fees)
                Child_Ticket.set("NO")
                Adult_Ticket.set("Yes")
                From_Destination.set("Chandigarh")
                To_Destination.set("Pune")
                Fee_Price.set(TotalCost)
                Total.set(TotalCost)
                Route.set("Direct")

                x = random.randit(109, 5876)
                randomRef = str(x)
                Reciept_Ref.set("TFL" + randomRef)
            elif (var9.get() == "Chandigarh->Pune" and var3.get() == 1 and var5.get() == 1):
                Tcost = float(75.21)
                Single = float(var12.get())
                Adult_Tax = "Rs.", str('%.2f' % ((Tcost * Single) * 0.05))
                Adult_Fees = "Rs.", str('%.2f' % ((Tcost * Single)))
                TotalCost = "Rs.", str('%.2f' % ((Tcost * Single) + ((Tcost * Single) * 0.05)))
                Tax.set(Adult_Tax)
                SubTotal.set(Adult_Fees)
                Ticketclass.set("Standard")
                TicketPrice.set(Adult_Fees)
                Child_Ticket.set("NO")
                Adult_Ticket.set("Yes")
                From_Destination.set("Chandigarh")
                To_Destination.set("Pune")
                Fee_Price.set(TotalCost)
                Total.set(TotalCost)
                Route.set("Direct")

                x = random.randit(109, 5876)
                randomRef = str(x)
                Reciept_Ref.set("TFL" + randomRef)
            elif (var9.get() == "Mumbai->Goa" and var3.get() == 1 and var4.get() == 1):
                Tcost = float(95.2)
                Single = float(var12.get())
                Adult_Tax = "Rs.", str('%.2f' % ((Tcost * Single) * 0.05))
                Adult_Fees = "Rs.", str('%.2f' % ((Tcost * Single)))
                TotalCost = "Rs.", str('%.2f' % ((Tcost * Single) + ((Tcost * Single) * 0.05)))
                Tax.set(Adult_Tax)
                SubTotal.set(Adult_Fees)
                Ticketclass.set("Standard")
                TicketPrice.set(Adult_Fees)
                Child_Ticket.set("NO")
                Adult_Ticket.set("Yes")
                From_Destination.set("Mumbai")
                To_Destination.set("Goa")
                Fee_Price.set(TotalCost)
                Total.set(TotalCost)
                Route.set("Direct")

                x = random.randit(109, 5876)
                randomRef = str(x)
                Reciept_Ref.set("TFL" + randomRef)
            elif (var9.get() == "Mumbai->Goa" and var3.get() == 1 and var5.get() == 1):
                Tcost = float(84.3)
                Single = float(var12.get())
                Adult_Tax = "Rs.", str('%.2f' % ((Tcost * Single) * 0.05))
                Adult_Fees = "Rs.", str('%.2f' % ((Tcost * Single)))
                TotalCost = "Rs.", str('%.2f' % ((Tcost * Single) + ((Tcost * Single) * 0.05)))
                Tax.set(Adult_Tax)
                SubTotal.set(Adult_Fees)
                Ticketclass.set("Standard")
                TicketPrice.set(Adult_Fees)
                Child_Ticket.set("NO")
                Adult_Ticket.set("Yes")
                From_Destination.set("Mumbai")
                To_Destination.set("Goa")
                Fee_Price.set(TotalCost)
                Total.set(TotalCost)
                Route.set("Direct")

                x = random.randit(109, 5876)
                randomRef = str(x)
                Reciept_Ref.set("TFL" + randomRef)
        def chkSbutton_Value():
            if(var10.get()==1):
                var12.set("")
                entSingle.focus()
                entSingle.configure(state=NORMAL)
                var11.set(0)
                entReturn.configure(state=DISABLED)
                var6.set("0")
            elif (var10.get()==0):
                entSingle.configure(state=DISABLED)
                var12.set("0")
        def chkRbuttion_Value():
            if (var11.get() == 1):
                var6.set("")
                entReturn.focus()
                entReturn.configure(state=NORMAL)
                var10.set(0)
                entSingle.configure(state=DISABLED)
                var12.set("0")
            elif var11.get() == 0:
                entReturn.configure(state=DISABLED)
                var6.set("0")
        def insert():
            if (var10.get()==1):
                PNopas=str(var12.get())+"S"
            elif(var11.get()==1):
                PNopas=str(var11.get())+"R"
            PName=Name.get()
            PAge=Age.get()
            PEmail=Email.get()
            PDeparture=From_Destination.get()
            PArrival=To_Destination.get()
            con=mysql.connect(host="localhost",user="root",password="1234",database="bd")
            cursor=con.cursor()
            cursor.execute("insert into reservation4 values('"+PName+"','"+PEmail+"','"+PAge+"','"+PDeparture+"','"+PArrival+"','"+PNopas+"')")
            cursor.execute("commit")

            insert = tkinter.messagebox.askyesno("Ticket confirmed","Press YES to cofirm ticket")
            if insert > 0:
                root.destroy()
            con.close()
######################PDF#########################

################Mail####################################################
            mail_content = "Name: "+PName+"\n"+"Age: "+PAge+"\n"+"From: "+PDeparture+"\n"+"To: "+PArrival+"\n"+"No. of Passenges: "+PNopas
            sender_address = 'passiticket542@gmail.com'
            with open("pass.txt", "r") as file:
                sender_pass = file.readline()
            receiver_address = PEmail
            # Setup the MIME
            message = MIMEMultipart()
            message['From'] = sender_address
            message['To'] = receiver_address
            message['Subject'] = 'Here is your train ticket.'  # The subject line
            # The body and the attachments for the mail
            message.attach(MIMEText(mail_content, 'plain'))
            # Create SMTP session for sending the mail
            session = smtplib.SMTP('smtp.gmail.com', 587)  # use gmail with port
            session.starttls()  # enable security
            session.login(sender_address, sender_pass)  # login with mail_id and password
            text = message.as_string()
            session.sendmail(sender_address, receiver_address, text)
            session.quit()
            print('Mail Sent')



       #=========================Lable Wiget==================================================
        lblRecipt= Label(frametopRight, font=('arial', 18, 'bold'), text="Travelling Ticket system", bd=5,pady=10, width=28, padx=4,justify='center')
        lblRecipt.grid(row=0, column=0)

        lblClass1 = Label(frameBottomRight, font=('arial', 14, 'bold'), text="Class", width=8,relief='sunken',justify='center')
        lblClass1.grid(row=0, column=0)

        lblClass2=Label(frameBottomRight,font=('arial',14,'bold'),width=8, relief='sunken',textvariable=Ticketclass,justify='center')
        lblClass2.grid(row=1,column=0)

        lblTicket1 = Label(frameBottomRight, font=('arial', 14, 'bold'), text="Ticket", width=8,relief='sunken',justify='center')
        lblTicket1.grid(row=0, column=1)

        lblTicket2=Label(frameBottomRight,font=('arial',14,'bold'),width=8, relief='sunken',textvariable=TicketPrice,justify='center')
        lblTicket2.grid(row=1,column=1)

        lblAdult1 = Label(frameBottomRight, font=('arial', 14, 'bold'), text="Adult", width=8,relief='sunken',justify='center')
        lblAdult1.grid(row=0, column=2)

        lblAdult2=Label(frameBottomRight,font=('arial',14,'bold'),width=8, relief='sunken',textvariable=Adult_Ticket,justify='center')
        lblAdult2.grid(row=1,column=2)

        lblChild1 = Label(frameBottomRight, font=('arial', 14, 'bold'), text="Child", width=8,relief='sunken',justify='center')
        lblChild1.grid(row=0, column=3)
###########################
        lblsp = Label(frameBottomRight, font=('arial', 14, 'bold'), width=36, height=2, relief='sunken', bg='lightgray')
        lblsp.grid(row=2, column=0, columnspan=4)
############################

        lblChild2=Label(frameBottomRight,font=('arial',14,'bold'),width=8, relief='sunken',textvariable=Child_Ticket,justify='center')
        lblChild2.grid(row=1,column=3)

        lblFrom1=Label(frameBottomRight,font=('airal',14,'bold'),text='From',width=8,relief='sunken',justify= 'center')
        lblFrom1.grid(row=3,column=1)
        lblFrom2=Entry(frameBottomRight,font=('arial',14,'bold'),width=8,relief='sunken',textvariable=From_Destination,justify='center')
        lblFrom2.grid(row=3,column=2)
########################################################################################
        lblTol=Label(frameBottomRight,font=('arial',14,'bold'),text="To",width=8,relief='sunken',justify='center')
        lblTol.grid(row=4,column=1)

        lblTo2=Entry(frameBottomRight,font=('arial',14,'bold'),width=8,relief='sunken',textvariable=To_Destination,justify='center')
        lblTo2.grid(row=4,column=2)

        lblPrice1 = Label(frameBottomRight,font=('arial', 14, 'bold'), text="Price", width=8, relief='sunken', justify='center')
        lblPrice1.grid(row=5, column=1)

        lblTo2 = Entry(frameBottomRight,font=('arial', 14, 'bold'), width=8, relief='sunken',textvariable=Fee_Price, justify='center')
        lblTo2.grid(row=5, column=2)
###################Space###################
        lblsp = Label(frameBottomRight, font=('arial', 14, 'bold'), width=36, height=2, relief='sunken', bg='lightgray')
        lblsp.grid(row=6, column=0, columnspan=4)
###################Space###################
        lblRefNo1=Label(frameBottomRight,font=('arial',14,'bold'),text="Ref No", width=8,relief='sunken',justify='center')
        lblRefNo1.grid(row=7,column=0)

        lblRefNo2=Label(frameBottomRight,font=('arial',14,'bold'),width=8, relief='sunken',textvariable=Reciept_Ref,justify='center')
        lblRefNo2.grid(row=8,column=0)

        lblTime1=Label(frameBottomRight,font=('arial',14,'bold'),text="Time", width=8,relief='sunken',justify='center')
        lblTime1.grid(row=7,column=1)

        lblTime2=Label(frameBottomRight,font=('arial',14,'bold'),width=8, relief='sunken',textvariable=time1,justify='center')
        lblTime2.grid(row=8,column=1)

        lblDate1=Label(frameBottomRight,font=('arial',14,'bold'),text="Date", width=8,relief='sunken',justify='center')
        lblDate1.grid(row=7,column=2)

        lblDate2=Label(frameBottomRight,font=('arial',14,'bold'),width=8, relief='sunken',textvariable=Date1,justify='center')
        lblDate2.grid(row=8,column=2)

        lblRoute1=Label(frameBottomRight,font=('arial',14,'bold'),text="Route", width=8,relief='sunken',justify='center')
        lblRoute1.grid(row=7,column=3)

        lblRoute2=Label(frameBottomRight,font=('arial',14,'bold'),width=8, relief='sunken',textvariable=Route,justify='center')
        lblRoute2.grid(row=8,column=3)
##################################################################################################################################
        Date1.set(time.strftime("%d/%m/%Y"))  #date
        time1.set(time.strftime("%H:%M")) #time
##################################################################################################################################
        lblClass= Label(topLeft1,font=('arial',16,'bold'),text="Class",bd=8).grid(row=0,column=0,sticky=W)
        chkStandard =Checkbutton(topLeft1,font=('arial',16,'bold'),text="Standard",variable=var1,onvalue=1,offvalue=0).grid(row=1,column=0,sticky=W)
        chkEconomy =Checkbutton(topLeft1,font=('arial',16,'bold'),text="Economy",variable=var2,onvalue=1,offvalue=0).grid(row=2,column=0,sticky=W)
        chkFirstClass =Checkbutton(topLeft1,font=('arial',16,'bold'),text="First Class",variable=var3,onvalue=1,offvalue=0).grid(row=3,column=0,sticky=W)

#################################################################################################################################

        lblSelect = Label(topLeft3, font=('arial',16,'bold'), text="Depature->Destination", bd=8).grid(row=0, column=0, sticky=W)
        lblDestination=Label(topLeft3, font=('arial',16,'bold'), text="Depature->Destination", bd=8).grid(row=0, column=0, sticky=W)
        cboDestination=ttk.Combobox(topLeft3,textvariable=var9,font=('arial',16,'bold'),state='readonly',width=10)
        cboDestination['value']=('Delhi->Kanpur','Kanpur->Chandigarh','Chandigarh->Pune','Mumbai->Goa')
        cboDestination.current(0)
        cboDestination.grid(row=0,column=1)
        chkAdult = Checkbutton(topLeft3, font=('arial',16,'bold'), text="Adult", variable=var4, onvalue=1,offvalue=0).grid(row=1, column=0, sticky=W)
        chkChild = Checkbutton(topLeft3, font=('arial',16,'bold'), text="Child", variable=var5, onvalue=1,offvalue=0).grid(row=2, column=0, sticky=W)

######################################################################Ticket##################################################################################
        lblTicketType = Label(topLeft2, font=('arial',16,'bold'), text="Ticket Type", bd=8).grid(row=0, column=0, sticky=W)
        chkSingle=Checkbutton(topLeft2, font=('arial',16,'bold'), text="Single", variable=var10, onvalue=1,offvalue=0,command=chkSbutton_Value)
        chkSingle.grid(row=1, column=0, sticky=W)
        entSingle = Entry(topLeft2, font=('arial', 16,'bold'), textvariable=var12, bd=2,width=8,state=DISABLED)
        entSingle.grid(row=1, column=1,sticky=W)
        chkReturn=Checkbutton(topLeft2, font=('arial', 16,'bold'), text="Return", variable=var11, onvalue=1,offvalue=0,command=chkRbuttion_Value)
        chkReturn.grid(row=2, column=0, sticky=W)
        entReturn = Entry(topLeft2, font=('arial', 16, 'bold'), textvariable=var6, bd=2,width=8,state=DISABLED)
        entReturn.grid(row=2, column=1,sticky=W)
        lblComment= Label(topLeft2, font=('arial', 16,'bold'), text="Comment", bd=8).grid(row=3, column=0, sticky=W)
        entComment=Entry(topLeft2,font=('arial',16,'bold'),textvariable=var7, bd=2,width=8).grid(row=3, column=1, sticky=W)
########################################################################################################################################################
        lblTax=Label(bottomLeft1,font=('arial',16,'bold'),text="Service Tax",bd=8).grid(row=0,column=0,sticky=W)
        entTax=Entry(bottomLeft1,font=('arial',16,'bold'),textvariable=Tax,bd=8,width=28).grid(row=0,column=1,sticky=W)
        lblSubTotal = Label(bottomLeft1, font=('arial', 16, 'bold'), text="Convenience Fee", bd=8).grid(row=1,column=0,sticky=W)
        entSubtotal = Entry(bottomLeft1, font=('arial', 16, 'bold'), textvariable=Tax, bd=8, width=28).grid(row=1,column=1,sticky=W)
        lblTotal=Label(bottomLeft1,font=('arial',16,'bold'),text="Total",bd=8).grid(row=2,column=0,sticky=W)
        entTotal = Entry(bottomLeft1, font=('arial', 16, 'bold'), textvariable=Tax, bd=8, width=28).grid(row=2,column=1,sticky=W)
########################################################################################################################################################
        lblName=Label(bottomLeft2,font=('arial',16,'bold'),text="Name",bd=8).grid(row=0,column=0,sticky=W)
        entName=Entry(bottomLeft2,font=('arial',16,'bold'),textvariable=Name,bd=8,width=28).grid(row=0,column=1,sticky=W)
        lblAge = Label(bottomLeft2, font=('arial', 16, 'bold'), text="Age", bd=8).grid(row=1, column=0, sticky=W)
        entAge = Entry(bottomLeft2, font=('arial', 16, 'bold'), textvariable=Age, bd=8, width=28).grid(row=1,column=1,sticky=W)
        lblEmail = Label(bottomLeft2, font=('arial', 16, 'bold'), text="Email", bd=8).grid(row=2, column=0, sticky=W)
        entEmail = Entry(bottomLeft2, font=('arial', 16, 'bold'), textvariable=Email, bd=8, width=28).grid(row=2,column=1,sticky=W)

########################################################################################################################################################
        btnTotal= Button(frameBottomRight,font=('arial',14,'bold'),text="Total",width=8, height=1, padx=2,pady=16,bd=4, command=Travel_Cost)
        btnTotal.grid(row=10,column=0)
        btnSubmit = Button(frameBottomRight, font=('arial', 14, 'bold'), text="Submit", width=8, height=1, padx=2, pady=16, bd=4, command=insert)
        btnSubmit.grid(row=10, column=1)
        btnReset = Button(frameBottomRight, font=('arial', 14, 'bold'), text="Reset", width=8, height=1, padx=2, pady=16, bd=4, command=Reset)
        btnReset.grid(row=10, column=2)
        btnExit = Button(frameBottomRight, font=('arial', 14, 'bold'), text="Exit", width=8, height=1, padx=2, pady=16, bd=4, command=iExit)
        btnExit.grid(row=10, column=3)
#############################################################Database Connection############################################################################




if __name__=='__main__':
    root=Tk()
    application=Train(root)
    root.mainloop()
#########################################################################################################################################


